### ISSUE TITLE
affichage de la partie gauche (blanche) de la tuile Blog à améliorer

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#14]
pour les petits écrans (mini portables), ça ajoute des ascenseurs...
![capture du 2016-09-08 16-44-11](https://cloud.githubusercontent.com/assets/7963908/18353737/82a81cfe-75e3-11e6-9db1-3e27d51dd24e.png)

**Comment by n-goncalves** [comment]
Fermé car plus d'actualité.
