### ISSUE TITLE
bouton "créer un blog" n’apparaît pas tout le temps

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#16]
![bouton creer blog](https://cloud.githubusercontent.com/assets/7963908/18437182/f975e12a-78fb-11e6-9ae0-0a6998906521.png)

**Comment by heleroy** [comment]
en même temps le blog de leur collège  n'était pas affiché dans les tuiles de droite et tout s'est affiché par la suite lors d'une autre connexion réalisée plus tard : aussi bien le bouton "créer un blog" que la tuile vers le blog du collège.

**Comment by Pilooz** [comment]
Ca doit être un problème de cadencement des requêtes http faites vers la plateforme de blog.
Celle qui fait l'authentification n'est peut-être pas terminée lorsque les droits pour l'affichage du bouton "créer un blog" sont calculés.
