### ISSUE TITLE
Le créateur du blog est admin de son blog mais ne peut pas aller sur son TB

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#18]
voir capture de ce qu'on obtient si on veut aller sur son TB après avoir créé son blog.
exemple : kyacin pour le blog 4e3clg-emilemalfroy.blogs.laclasse.com, pourtant il est bien nommé admin sur la liste des utilisateurs et quand on regarde son profil c'est noté "pas les droits sur ce site".
![capture du 2016-09-12 16-01-38](https://cloud.githubusercontent.com/assets/7963908/18438564/3f6c0a1e-7902-11e6-850b-f0836ac4b652.png)
![pas les droits suffisants](https://cloud.githubusercontent.com/assets/7963908/18438561/3f5605de-7902-11e6-94f2-c7b2cd21b866.png)
![admin yacin karim](https://cloud.githubusercontent.com/assets/7963908/18438562/3f564166-7902-11e6-8bd2-56733e757965.png)
![pas de role](https://cloud.githubusercontent.com/assets/7963908/18438563/3f58a46a-7902-11e6-9a58-2e0a65337ced.png)

**Comment by TestsCGI** [comment]
Test V3 - 2016 : reproduit sur l'environnement de développement

**Comment by Pilooz** [comment]
Peut-etre lié au #19 ?
A vérifier.
