### ISSUE TITLE
corriger le bug de profil "personnel administratif, technique ou d'encadrement" qui ne devrait pas récupérer les accès super admin sur la plateforme de blogs

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#19]
exemple login "floriandumont".
C'est sur le rôle "tech" que les droits de super amdin doivent être donnés sur la plateforme de WP, pas sur le profil.
![capture du 2016-09-12 16-55-05](https://cloud.githubusercontent.com/assets/7963908/18440963/5f9b1222-790b-11e6-9ddf-506af8059d0d.png)
![capture du 2016-09-12 16-54-43](https://cloud.githubusercontent.com/assets/7963908/18440962/5f943920-790b-11e6-817f-353aadc54278.png)

**Comment by heleroy** [comment]
ah bizarre, à moins que tu ais déjà bossé dessus entre temps... Mr BUCHLE (clg Ampère) a un profil personnel administratif et d'encadrement et du coup avait les droits de "subscribers" sur le blog du collège.. bizarre... Je l'ai remis en Editeur car ça devrait être le cas par défaut.

**Comment by Pilooz** [comment]
Un bug lié au logout de la plateforme Wordpress empêchait la dé-authentification.
Le log avec un Admin, pluis dé-log, puis re-log avec un autre profil provoquait donc le rattachement de ce profil au role super-admin.
