### ISSUE TITLE
Test V3 - 2016 / Tablettes ACER : pas d'accès aux blogs

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/ent-wp-management#20]
Après avoir appuyé sur la tuile blog, seul le portail s'affiche (bandeau noir). Sous le portail, la page est blanche.

**Comment by dlacroix** [comment]
Bug corrigé. Quelqu'un avait utilisé une fonctionnalité javascript ES6 dans les blogs. Cela ne servait à rien mais pose un problème de compatibilité avec les vieux navigateurs.
L'autre problème c'est qu'il faut METTRE A JOUR LES TABLETTES. C'est indispensable.

**Comment by TestsCGI** [comment]
test OK
