### ISSUE TITLE
Test V3 - 2016 : Gestion de l'inscription à un blog

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/ent-wp-management#21]
Lorsqu'un utilisateur de l'établissement Bac à Sable (par exemple un enseignant) s'inscrit à un blog de son établissement. Tous les autres utilisateurs de l'établissement visualise ce blog sur une des tuiles de la partie droite de l'écran et peuvent supprimer cette inscription (par exemple un parent).

**Comment by Pilooz** [comment]
Cette issue me semble liée à #19 (le problème de désauthentification) ?

**Comment by TestsCGI** [comment]
OK
