### ISSUE TITLE
gestion des rattachements (et détachements ?) aux blogs

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#24]
Actuellement, les nouveaux arrivants sur la V3 ne sont pas rattachés au blog de leur établissement ni au blog de leur classe, ou groupe d'élève. Ca devrait être le cas. On a simplement les rattachements figés sur l'état de la V2, donc rien n'est fait pour les nouveaux arrivants dans un établissement à la rentrée de sept 2016, et rien n'est prévu pour détacher sur WP les comptes qui sont détachés d'un établissement ou d'une classe sur l'ENT.

Il n'existe aucun lien entre le rattachement à un blog et le rattachement à son établissement, ses classes et ses groupes d'élèves, ni groupes libres.

**Comment by heleroy** [comment]
Les membres d'un groupe libre ne voient pas le groupe libre s'afficher dans le moteur de recherche de groupes libres (parmi les premiers résultats comme c'était (ou pas ?) le cas avant.

**Comment by dlacroix** [comment]
tout a changé depuis.
