### ISSUE TITLE
Provisionning d'utilisateur sans email laclasse

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/ent-wp-management#26]
Par exemple avec un utilisateur qui n'a qu'une adresse Académique. Dans ce cas Wordpress présente un formulaire de création qui demande l'email.
Vérifier le ticket CAS.

**Comment by Pilooz** [comment]
Non, c'est le fonctionnement normal. 
Je rappelle que la plateforme est mutualisée avec d'autres ENT et que légalement on ne peut pas (et on n'a pas les données) inscrire automatiquement l'utilisateur de la Loire ou de l'Ain sans que celui-ci ait lui-même renseigné son email. 
C'est pour ça qu'il y a ce formulaire.
