### ISSUE TITLE
V4 - bouton de création du blog absent

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/ent-wp-management#29]
Pour tous les types de comptes, sur les navigateurs chrome, mozilla et internet explorer plus de bouton de création des blogs

**Comment by dlacroix** [comment]
corrigé

**Comment by CharlotteRizzo** [comment]
Test du 9/08/17 : l'accès au bouton blog est fonctionnel pour tous les types de comptes, sur tous les navigateurs. 
Merci!
