### ISSUE TITLE
V4-Création de blog impossible

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#30]
Quand on fait la procédure pour créer un blog (d'établissement, classe ou autre type), on obtient l'erreur suivante : "une erreur s'est produite à la création du blog.'undefined " : la tuile est créée sur l'appli blog mais le blog n'existe pas sur la plateforme de blogs. Quand on clique sur la croix pour désinscrire / supprimer la tuile de ce blog, ça précise que l'utilisateur est désinscrit du blog.
On avait eu le même souci la semaine dernière pour la création du blog "Lalouma".

**Comment by dlacroix** [comment]
corrigé en dev et en prod

**Comment by CharlotteRizzo** [comment]
Test du 9/8/17 en prod : la création fonctionne bien pour tous les navigateurs et types de comptes
