### ISSUE TITLE
V4-Liste des "sites à reprendre" inaccessible depuis la migration

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#31]
si je suis déjà authentifiée sur l'ENT et que j'ouvre la page "blogs.laclasse.com/?ENT_action=REPRISE_DATA", je ne peux plus y aller. Habituellement, ça fonctionnait. 
cf capture jointe pour voir l'erreur.
Est-ce possible de rétablir cet accès pour que je puisse faire le tri des sites STP ?
![capture du 2017-07-21 10-23-50](https://user-images.githubusercontent.com/7963908/28455252-bb2669be-6dfe-11e7-9514-ccadfc1f26ea.png)

**Comment by dlacroix** [comment]
remise en place et adaptation de ce service. Il faudra vraiment le remplacer par qq chose de mieux.

**Comment by dlacroix** [comment]
cet outil n'existe plus, remplacé par l'admin panel
