### ISSUE TITLE
V4- certains cas d'inscription au blog d'un de ses groupes d'élève ou groupe libre ne sont pas possible

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#32]
exemple l'élève JABDOUS pour le blog du groupe 5LATIN "[Racines grecques et latines](http://racines-grecques-et-latines-victor-grignard.blogs.laclasse.com/)" affiche l'erreur "vous ne pouvez pas vous inscrire sur ce blog".
![capture du 2017-07-21 11-22-31](https://user-images.githubusercontent.com/7963908/28457558-e738d05c-6e06-11e7-917e-7d53e62f3b08.png)
![capture d ecran de 2017-07-21 11-21-50](https://user-images.githubusercontent.com/7963908/28457599-0f8e045a-6e07-11e7-8d35-1534548f07c4.png)

**Comment by heleroy** [comment]
même message si un enseignant/admin d'étab veut suivre un blog de groupe libre dont il fait partie. Exemple : njacotey pour le groupe libre "[Atelier MATh.en.JEANS](http://mathenjeans2016-2017.blogs.laclasse.com/)"

**Comment by heleroy** [comment]
Pour un prof, qui fait partie du groupe "5Latin", qui choisit de suivre le blog "racines grecques et latines", la tuile "racines grecques et latines" se crée mais le compte n'est pas généré sur WP et quand l'utilisateur cliquer sur le nom de la tuile pour accéder au blog en mode connecté, il n'a pas la barre noire l'indiquant comme connecté "abonné" sur le blog, et il n’apparaît pas dans la liste des utilisateurs du blog.

**Comment by heleroy** [comment]
Toutes les personnes inscrites comme "subscriber" à un blog ne voient pas la barre noire sur WP et l'utilisateur n'apparait pas dans la liste des utilisateurs.

**Comment by dlacroix** [comment]
normalement ces problèmes sont corrigés en dev et prod
