### ISSUE TITLE
V4-Le parent ne voit pas les blogs auxquels son enfant est inscrit

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/ent-wp-management#34]
exemple : le parent raitmessaoud2 ne voit pas le blog de la classe de 4ème 1 de son enfant jamairia

**Comment by dlacroix** [comment]
corrigé

**Comment by dlacroix** [comment]
il voit pas les blogs auxquels ses enfants sont inscrit mais les blogs des établissements et des groupes de ses enfants
