### ISSUE TITLE
V4-[amelioration] Peut on faciliter la visualiation complete du tableau des blogs ? 

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/ent-wp-management#35]
Dans le portail des blogs, on ne voit pas toujours bien le tableau des blogs (description et statut). 
Est-il possible de 
- l'adapter à la taille de la fenêtre (réduction de la taille des colonnes) 
-ou bien de permettre à l'utilisateur de scroler sans etre tout en bas, 
- ou bien de permettre d'agrandir la partie d'affichage à gauche?

**Comment by n-goncalves** [comment]
Fermé car plus d'actualité
