### ISSUE TITLE
v4 - Améliorer les performances des API des blogs

### ISSUE THREAD

**Issue by dlacroix** [laclasse-com/ent-wp-management#38]
C'est encore trop lent et c'est dommage. Il faudrait aller plus loin. C'est pas évident, cela risque de passer par un stockage différent de ce que fait WordPress MU (pas une table wp_{id}_options par blog mais une table wp_ent_options pour tous).

**Comment by n-goncalves** [comment]
Fait et passé en production hier.

A savoir, la récupération de blogs se fait via une jointure entre wp_blogs et wp_ent_options, donc si un blog n'a pas d'entrée dans wp_ent_options, il n'apparaitra pas dans les interfaces d'administration depuis laclasse-client.
